services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    env_file: .env
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  avito-banners:
    image: banners
    build: ./
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
    
networks:
  mynetwork:
    external: true